#' pelagichypoxia: A package for re-creating analyses in Moriarty et al. "Unexpected food web responses to low dissolved oxygen in an estuarine fjord"
#'
#' The pelagichypoxia package provides data, R and Stan code for analysis and for plotting.  Type help(...) for documentation of data and code
#'
#' @section data:
#' ctd_data
#' euphausiid_lengths
#' feeding_data
#' fish_backscatter
#' netdepths
#' zoop_blackscatter
#' zoopcomp

#' @section analysis and data loading functions:
#'    load_zoop_data,
#'    load_dietdata,
#'    get_Zoop_numbers_proportions,
#'    get_euphausiid_numbers,
#'    get_euphausiid_lengths,
#'    lood_sa_fish_data,
#'    run_all_bayesian_models
#' @section  data plotting functions:
#' plot_zoop_backscatter_data,
#' plot_temp_profiles,
#' plot_dietcomp_data,
#' plot_pnasc_vs_nasc,
#'
#' @section  results and other plotting functions:
#' The following can only be run if the entire R project is downloaded to your local machine,
#' as these call files generated by run_all_bayesian_models
#'
#' compare_loo,
#' calc_dothresh_posterior,
#' plot_backscatter_poseteriors,
#' plot_feeding_posteriors,
#'
#' @docType package
#' @name pelagichypoxia
NULL
